---
title: "Mini-Project 2"
author: "Your Name Here"
date: "October 31, 2017"
output: html_document
---


## Loading the data

This project is so interesting and relevant to my life!

```{r, include=FALSE}
library(tidyverse)
library(scales)
library(ggplot2)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
load("individuals.rda")
```


```{r}
#selecting variables from raw datasets
indiv <- individuals %>% select(cmte_id, transaction_amt, occupation, employer, state) %>% filter(state=="MA")
commit <- committees %>% select(cmte_id, cmte_name, cmte_type, cmte_party_affiliation, org_type)

#recoding org_type
commit$org_type[commit$org_type=="C"] <- "Corporation"
commit$org_type[commit$org_type=="L"] <- "Labor organization"
commit$org_type[commit$org_type=="M"] <- "Membership organization"
commit$org_type[commit$org_type=="T"] <- "Trade association"
commit$org_type[commit$org_type=="V"] <- "Cooperative"
commit$org_type[commit$org_type=="W"] <- "Corporation w/o capital stock"
commit$org_type[commit$org_type==" "] <- "NA"



#join
df <- indiv %>% left_join(commit, by ="cmte_id")
df <- df %>% group_by(org_type) %>% summarise(summ=sum(transaction_amt)) %>% filter(org_type %in% c("Corporation", "Labor organization", "Membership organization", "Trade association", "Cooperative", "Corporation w/o capital stock"))

#plot1
ggplot(df, aes(x=factor(org_type), y=summ)) + geom_bar(stat="identity", aes(fill=factor(org_type))) + theme(axis.text.x=element_text(angle=90, hjust=1))
```




```{r}
indiv_state <- individuals %>% select(cmte_id, transaction_amt, occupation, employer, state)
df_state <- indiv_state %>% left_join(commit, by ="cmte_id")

#join2
df_state <- df_state %>% group_by(org_type) %>% summarise(summ=sum(transaction_amt)) %>% filter(org_type %in% c("Corporation", "Labor organization", "Membership organization", "Trade association", "Cooperative", "Corporation w/o capital stock"))

#plot2
ggplot(df_state, aes(x=factor(org_type), y=summ)) + geom_bar(stat="identity", aes(fill=factor(org_type))) + theme(axis.text.x=element_text(angle=90, hjust=1)) +   facet_wrap(~state)
indiv_state <- individuals %>% select(cmte_id, transaction_amt, occupation, employer, state)
df_state <- indiv_state %>% left_join(commit, by ="cmte_id")


#df_state <- df_state %>% group_by(state, org_type) %>% summarise(summ=sum(transaction_amt)) %>% filter(org_type != "NA", state !=" ")
#View(df_state)

#ggplot(df_state, aes(x=factor(org_type), y=summ)) + geom_bar(stat="identity", aes(fill=factor(org_type))) + theme(axis.text.x=element_text(angle=90, hjust=1)) +   facet_wrap(~state)

```

